global using NorthWind.Entities.Interfaces;
global using Microsoft.Extensions.DependencyInjection;
global using NorthWind.Entities.Services;
global using NorthWind.Entities.Exceptions;
global using NorthWind.Entities.ValueObject;
global using System.Text.Json;
global using NorthWind.Entities.Interfaces.Events;            
global using Microsoft.Extensions.Logging;
global using System.Linq.Expressions;