global using NorthWind.Sales.BusinessObjects.DTOs.CreateOrder;
global using Microsoft.AspNetCore.Components;
global using NorthWind.Sales.WebApiGateway;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using NorthWind.Entities.Interfaces;
global using NorthWind.Sales.BlazorClient;
global using NorthWind.Sales.Validalitor.CreateOrder;
global using NorthWind.Entities.Exceptions;